# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: deploy via ssh commands
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd metricamusic
            git pull
            docker build -t metricamusic .
            docker stop metricamusic || true
            docker rm metricamusic || true
            docker run --rm -dp 99:80 --name metricamusic metricamusic
          host: metricamusic.it
          user: root
          key: ${{ secrets.PRIVATE_KEY}}
          
